VictorK react-toggle-switch-component (1st submission)
vkalinkin/rc0521-code-solutions pull request #120
Opened 2021-07-09 23:28 UTC by vkalinkin

![toggle 1](https://user-images.githubusercontent.com/33187217/125144397-9c99a100-e0d2-11eb-84e8-18ec9d4c159d.PNG)
![toggle 2](https://user-images.githubusercontent.com/33187217/125144399-9efbfb00-e0d2-11eb-82b3-77a55503149b.PNG)

2021-07-09 23:32 UTC, Zhiwutian requested changes
Very nice work Victor, a small update to polish the render method!

2021-07-09 23:32 UTC, Zhiwutian commented on react-toggle-switch-component/src/toggle-switch.jsx
> +    if (this.state.isOn) {
The only update I would do here is move the logic into a different method and have that method return an object with the className, circleName, and spanText values so you can use that object to set the values in the JSX.

2021-07-11 01:12 UTC, vkalinkin commented
![toggle 3](https://user-images.githubusercontent.com/33187217/125180046-616aa100-e1aa-11eb-908c-d6075d527538.PNG)

2021-07-12 17:57 UTC, scbowler approved these changes
Looks good! 👍

2021-07-12 17:57 UTC, merged