Big o notation
vkalinkin/rc0521-code-solutions pull request #133
Opened 2021-08-02 22:49 UTC by vkalinkin

![big o](https://user-images.githubusercontent.com/33187217/127933172-9e20dd0a-5af3-4718-afcd-87d77edc0b58.PNG)

2021-08-02 23:18 UTC, scbowler requested changes
Looking good, just a few spots to cleanup. Let us know if you have any questions.

2021-08-02 23:18 UTC, scbowler commented on big-o-notation/big-o.js
> +    let i = 0;                      // 1 * n = O(n)
The assignment part of the for loop only runs once, not after every iteration so this line would still be `1 * 1`

2021-08-02 23:18 UTC, scbowler commented on big-o-notation/big-o.js
> +      unique[unique.length] = word; // 3 * n = O(3n) ~= 0(n)
This is actually only 2 operations, accessing the `length` property and the assignment

2021-08-02 23:18 UTC, scbowler commented on big-o-notation/big-o.js
> +    let i = 0;                      // 1 * n = O(n)
This only happens once for this loop so it would be `1 * 1`

2021-08-02 23:18 UTC, scbowler commented on big-o-notation/big-o.js
> +    let isUnique = true;            // 1 * 1 = O(1)
This is in the loop so it will be `1 * n`

2021-08-02 23:18 UTC, scbowler commented on big-o-notation/big-o.js
> +      let c = 0;                    // 1 * n^2 = O(n^2)
This only happens once each time this loop runs but it will still run once for each of the parent loop so it should be `1 * n`

2021-08-02 23:18 UTC, scbowler commented on big-o-notation/big-o.js
> +      const comparing = words[c];   // 3 * n^2 = O(3n^2) ~= 0(n^2)
This is 2 operations so `2 * n^2`

2021-08-02 23:18 UTC, scbowler commented on big-o-notation/big-o.js
> +      unique[unique.length] = word; // 3 * n^2 = O(3n^2) ~= 0(n^2)
Same as the previous function this is actually only 2 operations `2 * n^2`

2021-08-02 23:26 UTC, vkalinkin commented
![big o 2](https://user-images.githubusercontent.com/33187217/127935625-d867909e-8076-4423-b20d-bb727c2f4c5f.PNG)

2021-08-03 01:37 UTC, scbowler approved these changes
Looks good! 👍 

A few FYI comments, no resubmission required

2021-08-03 01:37 UTC, scbowler commented on big-o-notation/big-o.js
> +    const word = words[i];          // 3 * n = O(3n) ~= 0(n)
This is `2 * n` property access and assignment

2021-08-03 01:37 UTC, scbowler commented on big-o-notation/big-o.js
> +      unique[unique.length] = word; // 2 * n^2 = O(2n^2) ~= 0(n^2)
These 2 lines are outside of the second for loop so they are only `n` not `n^2`

2021-08-03 01:37 UTC, scbowler commented on big-o-notation/big-o.js
> +  return unique;                    // 1 * n^2 = O(n^2)
This is ouside of both loops so would just be `1 * 1`

2021-08-03 01:37 UTC, merged